package entity;
// Generated Mar 29, 2019 7:52:01 PM by Hibernate Tools 4.3.1



/**
 * Accountant generated by hbm2java
 */
public class Accountant  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String gender;
     private String phone;
     private String userId;
     private String email;
     private String password;

    public Accountant() {
    }

    public Accountant(String name, String gender, String phone, String userId, String email, String password) {
       this.name = name;
       this.gender = gender;
       this.phone = phone;
       this.userId = userId;
       this.email = email;
       this.password = password;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


