package entity;
// Generated Mar 29, 2019 7:52:01 PM by Hibernate Tools 4.3.1



/**
 * Fee generated by hbm2java
 */
public class Fee  implements java.io.Serializable {


     private Integer id;
     private int stuId;
     private double totalFee;
     private double semesterFee;
     private double semesterDue;

    public Fee() {
    }

    public Fee(int stuId, double totalFee, double semesterFee, double semesterDue) {
       this.stuId = stuId;
       this.totalFee = totalFee;
       this.semesterFee = semesterFee;
       this.semesterDue = semesterDue;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getStuId() {
        return this.stuId;
    }
    
    public void setStuId(int stuId) {
        this.stuId = stuId;
    }
    public double getTotalFee() {
        return this.totalFee;
    }
    
    public void setTotalFee(double totalFee) {
        this.totalFee = totalFee;
    }
    public double getSemesterFee() {
        return this.semesterFee;
    }
    
    public void setSemesterFee(double semesterFee) {
        this.semesterFee = semesterFee;
    }
    public double getSemesterDue() {
        return this.semesterDue;
    }
    
    public void setSemesterDue(double semesterDue) {
        this.semesterDue = semesterDue;
    }




}


