package entity;
// Generated Mar 29, 2019 7:52:01 PM by Hibernate Tools 4.3.1


import dao.TeacherDao;
import java.util.Date;
import java.util.List;
import javax.faces.bean.ManagedBean;

/**
 * Teacher generated by hbm2java
 */
@ManagedBean
public class Teacher  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String department;
     private String password;
     private String phone;
     private String gender;
     private String userId;
    
     private String course;
     private List tlist;

    public Teacher() {
    }

    public Teacher(String name, String department, String password, String phone, String gender, String userId, Date date, String course) {
       this.name = name;
       this.department = department;
       this.password = password;
       this.phone = phone;
       this.gender = gender;
       this.userId = userId;
      
       this.course = course;
    }

    public List getTlist() {
        return tlist;
    }

    public void setTlist(List tlist) {
        this.tlist = tlist;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
   
    public String getCourse() {
        return this.course;
    }
    
    public void setCourse(String course) {
        this.course = course;
    }

    public void saveT(){
   TeacherDao td= new TeacherDao();
           td.addteacher(this);   
    }
    
public void deleteT(){
    TeacherDao td= new TeacherDao();
            td.deleteTr(id);
}

public List<Teacher> searchT(){
    TeacherDao td = new TeacherDao();
    List <Teacher>tl = td.getById(id);
    id= tl.get(0).id;
    name=tl.get(0).name;
    department= tl.get(0).department;
    
    return tl;
}
public void updateT(){
    TeacherDao td = new TeacherDao();
    td.updateTr(this);
    
            
}
public List<Teacher> allT(){
    TeacherDao td = new TeacherDao();
    List<Teacher> tlis = td.allTeacher();
    return tlis; 
}
    



}


